spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: post-service
            uri: lb://post-service
            predicates:
              - Path=/api/v1/post/**
          - id: user-service
            uri: lb://user-service
            predicates:
              - Path=/api/v1/user/**
          - id: ai-service
            uri: lb://ai-service
            predicates:
              - Path=/api/v1/ai/**
server:
  port: 8080
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka